//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IR_Btree_Indexer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocsWords
    {
        public int DocId { get; set; }
        public int WordId { get; set; }
        public string Locations { get; set; }
    
        public virtual Doc Doc { get; set; }
        public virtual Word Word { get; set; }
    }
}
